services:
    nginx:
        image: nginx:alpine
        container_name: green_market_proxy
        restart: unless-stopped
        ports:
            - '80:80' # Port HTTP standard
            - '443:443' # Port HTTPS (Optionnel pour l'instant, indispensable pour le SSL)
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
            - ./frontend/dist:/var/www/frontend:ro
        depends_on:
            - frontend
            - backend

    frontend:
        # Image frontend buildée et publiée sur Docker Hub
        image: vials512t/greenmarket:frontend-latest

        # Nom du container
        container_name: green_market_frontend

        # Redémarre automatiquement sauf arrêt manuel
        restart: unless-stopped

        env_file:
            - .env

        depends_on:
            - backend

    backend:
        # Image backend publiée sur Docker Hub
        image: vials512t/greenmarket:backend-latest

        container_name: green_market_backend

        restart: unless-stopped

        ports:
            - '80'

        env_file:
            - .env

        depends_on:
            - db

    db:
        image: mysql:8.0

        container_name: green_market_db

        restart: unless-stopped

        env_file:
            - .env

        volumes:
            # Persistance des données MySQL
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest

        container_name: green_market_phpmyadmin

        restart: unless-stopped

        env_file:
            - .env

        ports:
            # phpMyAdmin accessible sur 127.0.0.1:8080
            - '127.0.0.1:8080:80'

        depends_on:
            - db

volumes:
    # Volume Docker persistant pour MySQL
    db_data:
