services:
    frontend:
        # Image frontend buildée et publiée sur Docker Hub
        image: vials512t/greenmarket:frontend-latest

        # Nom du container
        container_name: green_market_frontend

        # Redémarre automatiquement sauf arrêt manuel
        restart: unless-stopped

        ports:
            # Expose le frontend sur le port 5173
            - '5173:5173'

        env_file:
            - .env

        depends_on:
            - backend

    backend:
        # Image backend publiée sur Docker Hub
        image: vials512t/greenmarket:backend-latest

        container_name: green_market_backend

        restart: unless-stopped

        ports:
            # Apache/PHP exposé sur le port 8000
            - '8000:80'

        env_file:
            - .env

        depends_on:
            - db

    db:
        image: mysql:8.0

        container_name: green_market_db

        restart: unless-stopped

        env_file:
            - .env

        volumes:
            # Persistance des données MySQL
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin:latest

        container_name: green_market_phpmyadmin

        restart: unless-stopped

        env_file:
            - .env

        ports:
            # phpMyAdmin accessible sur localhost:8080
            - '8080:80'

        depends_on:
            - db

volumes:
    # Volume Docker persistant pour MySQL
    db_data:
